### PR TITLE
nfc: add NFC supoort

### PR DESCRIPTION
**Pull request by vm03**

### CODE REVIEW

**Comment by BeYkeRYkt** [comment]
For a common tree, this does not make sense, since the device may not have a NFC module (like Xiaomi devices)

**Comment by vm03** [comment]
Any other device use cyanogen_msm8937-common?
I think marmite need to decommonize...

**Comment by BeYkeRYkt** [comment]
Perhaps, but I want to keep structure of trees as left from Cyanogen.

**Comment by vm03** [comment]
As i know cyanogen*common for CyanogenOS form inc.
No more cyanogenos, no more inc... 
If no more devices can use this common, he is meaningless.

**Comment by vm03** [comment]
Hm... But, i have not seen nfc on marmite... and what the fix is unclear...

**Comment by vm03** [comment]
NFC works without it....

**Pull request closed without merging**
